Add mapping to hazelcast-platform-operator FBC operator
The operator rendering process has changed and a new mapping in the
ci.yaml file determines a target location of the catalog. This update is
based on recent change introduced in operator pipelines.

In case something is not clear please reach out repository maintainers.

Signed-off-by: Ales Raszka <araszka@redhat.com>

diff --git a/operators/hazelcast-platform-operator/Makefile b/operators/hazelcast-platform-operator/Makefile
--- a/operators/hazelcast-platform-operator/Makefile
+++ b/operators/hazelcast-platform-operator/Makefile
@@ -4,14 +4,8 @@
 # The makefile should be placed in the root of the operator repository.
 # for example at: <operator-repo>/operators/<operator-name>/Makefile
 
-# A user can customize "catalog" target to generate the operator catalog in a way
-# that suits the operator.
-# OPM allows for the generation of catalogs using different templates.
-# - basic: generates a basic catalog
-# - semver: generates a catalog with semver versioning
-
-PDW=$(shell pwd)
-OPERATOR_NAME=$(shell basename $(PDW))
+PWD=$(shell pwd)
+OPERATOR_NAME=$(shell basename $(PWD))
 TOPDIR=$(abspath $(dir $(PWD))/../)
 BINDIR=${TOPDIR}/bin
 
@@ -20,82 +14,88 @@ export PATH := $(BINDIR):$(PATH)
 # A place to store the generated catalogs
 CATALOG_DIR=${TOPDIR}/catalogs
 
-# A place to store the operator catalog templates
-OPERATOR_CATALOG_TEMPLATE_DIR = ${PDW}/catalog-templates
+# The operator pipeline image to use for the fbc-onboarding target
+OPERATOR_PIPELINE_IMAGE ?= quay.io/redhat-isv/operator-pipelines-images:released
 
-# A list of OCP versions to generate catalogs for
-# This list can be customized to include the versions that are relevant to the operator
-# DO NOT change this line (except for the versions) if you want to take advantage
-# of the automated catalog promotion
-OCP_VERSIONS=$(shell echo "v4.12 v4.13 v4.14 v4.15 v4.16" )
+# Define the paths for both auth files
+DOCKER_CONFIG := $(HOME)/.docker/config.json
+CONTAINERS_AUTH := $(XDG_RUNTIME_DIR)/containers/auth.json
 
 
-#
 .PHONY: fbc-onboarding
-fbc-onboarding: fbc-onboarding-deps ${BINDIR}/opm clean
-	fbc-onboarding \
-		--repo-root $(TOPDIR) \
-		--operator-name $(OPERATOR_NAME) \
-		--cache-dir $(TOPDIR)/.catalog_cache \
-		--verbose
+fbc-onboarding: clean
+	@if [ -f $(DOCKER_CONFIG) ]; then \
+		echo "Using Docker config file: $(DOCKER_CONFIG)"; \
+		CONFIG_VOLUME="-v $(DOCKER_CONFIG):/root/.docker/config.json"; \
+	elif [ -f $(CONTAINERS_AUTH) ]; then \
+		echo "Using containers auth file: $(CONTAINERS_AUTH)"; \
+		CONFIG_VOLUME="-v $(CONTAINERS_AUTH):/root/.docker/config.json"; \
+	else \
+		echo "No authentication file found."; \
+	fi; \
+	podman run \
+		--rm \
+		--user $(id -u):$(id -g) \
+		--security-opt label=disable \
+		--pull always \
+		-v $(TOPDIR):/workspace \
+		$$CONFIG_VOLUME \
+		$(OPERATOR_PIPELINE_IMAGE) fbc-onboarding \
+			--repo-root /workspace \
+			--operator-name $(OPERATOR_NAME) \
+			--cache-dir /workspace/.catalog_cache
 
-.PHONY: catalog
-# replace this stub with one customized to serve your needs ... some examples below
+.PHONY: catalogs
 
-# here are a few examples of different approaches to fulfilling this target
-# comment out / customize the one that makes the most sense, or use them as examples in defining your own
-#
-# --- BASIC TEMPLATE ---
-catalog: basic
-#
-# --- SEMVER TEMPLATE ---
-#catalog: semver
-
-
-# basic target provides an example FBC generation from a `basic` template type.
-# this example takes a single file as input and generates a well-formed FBC operator contribution as an output
-.PHONY: basic
-basic: ${BINDIR}/opm clean
-	for version in $(OCP_VERSIONS); do \
-		mkdir -p ${CATALOG_DIR}/$${version}/${OPERATOR_NAME}/ && \
-		${BINDIR}/opm alpha render-template basic -o yaml ${OPERATOR_CATALOG_TEMPLATE_DIR}/$${version}.yaml > ${CATALOG_DIR}/$${version}/${OPERATOR_NAME}/catalog.yaml; \
-	done
+# Catalogs are generated based on the mapping in ci.yaml file
+# The example of the mapping is:
+# fbc:
+#   enabled: true
+#   catalog_mapping:
+#     - template_name: basic.yaml
+#       catalog_names: ["v4.14", "v4.15", "v4.16"]
+#       type: olm.template.basic
+#     - template_name: semver.yaml
+#       catalog_names: ["v4.13", "v4.17"]
+#       type: olm.semver
+catalogs: ${BINDIR}/render_catalogs.sh ${BINDIR}/opm ${BINDIR}/yq clean
+	@echo "Rendering catalogs from templates"
+	@${BINDIR}/render_catalogs.sh
 
 
-# semver target provides an example FBC generation from a `semver` template type.
-# this example takes a single file as input and generates a well-formed FBC operator contribution as an output
-.PHONY: semver
-semver: ${BINDIR}/opm clean
-	for version in $(OCP_VERSIONS); do \
-		mkdir -p ${CATALOG_DIR}/$${version}/${OPERATOR_NAME}/ && \
-		${BINDIR}/opm alpha render-template semver -o yaml  ${OPERATOR_CATALOG_TEMPLATE_DIR}/$${version}.yaml > ${CATALOG_DIR}/$${version}/${OPERATOR_NAME}/catalog.yaml; \
-	done
-
-#
-# validate target illustrates FBC validation
+# validate-catalogs target illustrates FBC validation
 # all FBC must pass opm validation in order to be able to be used in a catalog
-.PHONY: validate
-validate: ${BINDIR}/opm
-	${BINDIR}/opm validate $(CATALOG_DIR) && echo "catalog validation passed" || echo "catalog validation failed"
+.PHONY: validate-catalogs
+validate-catalogs: ${BINDIR}/opm
+	@find ${TOPDIR}/catalogs -type d -name fbc-test-operator -exec \
+		sh -c '${BINDIR}/opm validate $$(dirname "{}") && echo "✅ Catalog validation passed: {}" || echo "❌ Catalog validation failed: {}"' \;
 
 .PHONY: create-catalog-dir
 create-catalog-dir:
-	mkdir -p $(CATALOG_DIR)
+	@mkdir -p $(CATALOG_DIR)
 
 .PHONY: clean
 clean: create-catalog-dir
-	find $(CATALOG_DIR) -type d -name ${OPERATOR_NAME} -exec rm -rf {} +
+	@echo "Cleaning up the operator catalogs from $(CATALOG_DIR)"
+	@find $(CATALOG_DIR) -type d -name ${OPERATOR_NAME} -exec rm -rf {} +
 
-# fbc-onboarding-deps installs the fbc-onboarding tool using pip
-.PHONY: fbc-onboarding-deps
-fbc-onboarding-deps:
-	pip install git+https://github.com/redhat-openshift-ecosystem/operator-pipelines.git
 
 OS=$(shell uname -s | tr '[:upper:]' '[:lower:]')
 ARCH=$(shell uname -m | sed 's/x86_64/amd64/')
 
-# Automatically download the opm binary
+# Automatically download the binaries and scripts and place them in the bin directory
 OPM_VERSION ?= v1.46.0
 ${BINDIR}/opm:
 	if [ ! -d ${BINDIR} ]; then mkdir -p ${BINDIR}; fi
 	curl -sLO https://github.com/operator-framework/operator-registry/releases/download/$(OPM_VERSION)/$(OS)-$(ARCH)-opm && chmod +x $(OS)-$(ARCH)-opm && mv $(OS)-$(ARCH)-opm ${BINDIR}/opm
+
+YQ_VERSION ?= v4.45.1
+${BINDIR}/yq:
+	if [ ! -d ${BINDIR} ]; then mkdir -p ${BINDIR}; fi
+	curl -sLO https://github.com/mikefarah/yq/releases/download/$(YQ_VERSION)/yq_$(OS)_$(ARCH) && mv yq_$(OS)_$(ARCH) ${BINDIR}/yq && chmod +x ${BINDIR}/yq
+
+${BINDIR}/render_catalogs.sh:
+	if [ ! -d ${BINDIR} ]; then mkdir -p ${BINDIR}; fi
+	curl -sLO https://raw.githubusercontent.com/redhat-openshift-ecosystem/operator-pipelines/main/fbc/render_catalogs.sh
+	mv render_catalogs.sh ${BINDIR}/render_catalogs.sh
+	chmod +x ${BINDIR}/render_catalogs.sh
